config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save {self.email = email.downcase}
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 150 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe
  
  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader:picture, PictureUploader
  validate :picture_size
  default_scope -> {order(updated_at: :desc)}
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to :back
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @chef = Chef.new
  end
  
  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Your account has been created successfully"
      session[:chef_id] = @chef.id
      redirect_to chef_path(@chef)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @chef.update(chef_params)
      flash[:success] = "Your profile has been updated successfully"
      redirect_to recipes_path #TODO change to show chef page
    else
      render 'edit'
    end
  end
  
  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
  end
  
  private
  
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password)
    end
    
    def set_chef
      @chef = Chef.find(params[:id])
    end
    
    def require_same_user
      if current_user != @chef
        flash[:danger] = "You can only edit your own profile"
        redirect_to root_path
      end
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end
  
  def create
    chef = Chef.find_by(email: params[:email])
    
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "You are logged in"
      redirect_to recipes_path
    else
      flash.now[:danger] = "Your e-mail or password does not match"
      render 'new'
    end
  end
  
  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end
  
  def show
    
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    
    if @recipe.save
      flash[:success] = "Your recipe was created successfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was successful"
    else
      flash[:danger] = "You can only vote on a recipe once"
    end
    redirect_to :back
  end
  
  private
  
  def recipe_params
    params.require(:recipe).permit(:name, :summary, :description, :picture)
  end
  
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
  
  def require_same_user
    if current_user != @recipe.chef
      flash[:danger] = "You can only edit your own recipes"
      redirect_to recipes_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @chef do |f| %>
      <%= f.label :chefname %>
      <%= f.text_field :chefname %>
      
      <%= f.label :email %>
      <%= f.email_field :email %>
      
      <%= f.label :password %>
      <%= f.password_field :password %>
      
      <%= f.submit(@chef.new_record? ? 'Register' : 'Update', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

app/views/chefs/index.html.erb
<h1>Chefs</h1>
<hr/>

<ul class="nav nav-tabs">
  <li>
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li class="active">
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate %>

<% @chefs.each do |chef| %>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <section class="chef_info center">
      <%= link_to gravatar_for(chef, size: 100), chef_path(chef) %>
      <h5>Chef name: <%= chef.chefname %></h5>
    </section>
  </div>
</div>
<% end %>

<%= will_paginate %>

app/views/chefs/new.html.erb
<h1>Register your account</h1>

<%= render 'form' %>

app/views/chefs/show.html.erb
<h1>Chef: <%= @chef.chefname %></h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @chef, size: 200 %>
    <hr/>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3>Recipes</h3>
    <%= will_paginate @recipes %>
  </div>
</div>
<% @recipes.each do |recipe| %>
<div class="row">
  <div class="col-lg-6 well col-lg-offset-3">
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    <p><%= recipe.summary %></p>
    <p>
      <span class="quiet">
        <small>created <%= time_ago_in_words(recipe.created_at) %> ago</small>
      </span> <br/>
      <% if recipe.created_at != recipe.updated_at %>
      <span class="quiet">
        <small> updated <%= time_ago_in_words(recipe.updated_at) %> ago</small>
      </span>
      <% end %>
    </p>
    <div class="pull-right">
      <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
      <% end %>
      <span class="spaces"></span>
      <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  &copy; 2016 TAIF
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "myRecipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
    <div class="nav_item">
      <%= link_to "link 1", "", class: "btn btn-default btn-warning" %>
    </div>
    <div class="nav_item">
      <%= link_to "link 2", "", class: "btn btn-default btn-warning" %>
    </div>
<% if logged_in? %>    
    <div class="nav_item">
      <%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
    </div>
    <ul class="nav_item">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          <%= current_user.chefname %> <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to "View profile", chef_path(current_user) %></li>
          <li><%= link_to "Edit profile", edit_chef_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Logout", logout_path %></li>
        </ul>
      </li>
    </ul>
<% else %>    
    <div class="nav_item">
      <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
    </div>
<% end %>    
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/logins/new.html.erb
<h1>Login</h1>

<div class="row">
  <div class="well col-md-6 col-md-offset-3">
    <%= form_tag '/login' do %>
      <%= label_tag :email %>
      <%= text_field_tag :email %>
      
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      
      <%= submit_tag 'Login', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to My Recipes App</h1>
  <h2>This is the home page</h2>
  
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">View recipes as guest user</h3>
    <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
    <p>
      <%= link_to "Browse recipe listings", recipes_path, class: "btn btn-warning btn-small" %>
    </p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">Sign in to your account</h3>
    <h2 class="left">Add/update your recipes, create reviews, like/dislike recipes and much much more</h2>
    <p>
      <%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %>
    </p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">View recipes as guest user</h3>
    <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
    <p>
      <%= link_to "Browse recipe listings", "", class: "btn btn-warning btn-small" %>
    </p>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @recipe do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      
      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $("#recipe_picture").bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file");
    }
  });
</script>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<hr/>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
<div class="row">
  <div class="col-md-2">
    <section class="chef_info center">
      <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
      <h5>Chef name: <%= recipe.chef.chefname %></h5>
    </section>
  </div>
  <div class="col-lg-6 well">
    <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
    <p><%= recipe.summary %></p>
    <p>
      <span class="quiet">
        <small>created <%= time_ago_in_words(recipe.created_at) %> ago</small>
      </span> <br/>
      <% if recipe.created_at != recipe.updated_at %>
      <span class="quiet">
        <small> updated <%= time_ago_in_words(recipe.updated_at) %> ago</small>
      </span>
      <% end %>
    </p>
    <div class="pull-right">
      <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
      <% end %>
      <span class="spaces"></span>
      <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
  </div>
</div>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<h1>Create a new recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
    <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
  </div>
  <div class="col-md-8">
<% if logged_in? and @recipe.chef == current_user %>
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
<% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture %>
    </div>
    <div class="well">
      <p><strong>Steps: </strong></p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %>
        <span class="spaces"></span>
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to "Return to recipes' listing", recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="alert alert-danger col-md-8 col-md-offset-2">
    <h5>Please correct the following errors:</h5>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>  
</div>
<% end %>